name: Publish Image

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        uses: actions/cache@v2
        with:
          path: /tmp/build-cache
          key: build-${{ github.sha }}
          restore-keys: |
            build

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push an Image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ikanag0/riscv-toolchain:latest
          cache-from: type=local,src=/tmp/build-cache
          cache-to: type=local,dest=/tmp/build-cache-new

      # Work around: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
      - name: Move Cache
        run: |
          rm -rf /tmp/build-cache
          mv /tmp/build-cache-new /tmp/build-cache

