name: Publish Image

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push an Image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ikanag0/riscv-toolchain:latest
          cache-from: type=local,src=/build-cache
          cache-to: type=local,dest=/build-cache-new

      # Work around: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
      - name: Move Cache
        run: |
          rm -rf /build-cache
          mv /build-cache-new /build-cache

