name: Publish Image

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ DOCKER_HUB_USERNAME }}
          password: ${{ DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push an Image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ikanag0/riscv-toolchain:latest

